### ISSUE TITLE
This seems to miss legacy facts that are being interpolated

### ISSUE THREAD

**Issue by genebean** [mmckinst/puppet-lint-legacy_facts-check#15]
The check misses this:

```
default: { notify { "No pacakage foo for ${osfamily}": } }
```

**Comment by mmckinst** [comment]
It is missing it because it expects a top scope fact like `$::osfamily`. https://github.com/mmckinst/puppet-lint-top_scope_facts-check will fix that for you.

I'll add something to the documentation that it will only find top scope facts.

**Comment by mmckinst** [comment]
Can you provide a test case where it isn't working? 

`$::osfamily` and `$osfamily` are actually one of the [test cases](https://github.com/mmckinst/puppet-lint-legacy_facts-check/blob/8bc5307ddb06e2b089b7ae91bea575f413ccbed3/spec/puppet-lint/plugins/legacy_facts_spec.rb#L22-L44) and is passing in the most recent test: https://travis-ci.org/mmckinst/puppet-lint-legacy_facts-check/jobs/492503967

**Comment by genebean** [comment]
The example from my original report was pulled directly from a manifest where detection wasn't working.

**Comment by mmckinst** [comment]
OK. I see the problem now. its failing when the variable has double quotes around it, even if it is correctly top scoped. The below example is failing to be found by legacy_facts-check:

`notify { "Example \$::osfamily $::osfamily": }`

**Comment by genebean** [comment]
Any idea why the double quotes are the issue? FWIW, all interpolated facts in a string would be double quoted as that's required to make the interpolation happen.

**Comment by mmckinst** [comment]
How the puppet-lint works under the hood is beyond my understanding :(.

I did find a fix at https://github.com/mmckinst/puppet-lint-legacy_facts-check/pull/18 . Does that work on your code?

It is weird because I swear I've used this on top scope variables inside quotes, although maybe I've always used top scope variables with curly braces around them like `${::osfamily}` since it works fine on them.

**Comment by genebean** [comment]
I’ll give it a try and report back 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mmckinst** [comment]
Did the fix at https://github.com/mmckinst/puppet-lint-legacy_facts-check/pull/18 work?

**Comment by mmckinst** [comment]
@genebean Did you get a chance to test the fix? It worked in the test case I came up with in the PR.

**Comment by mmckinst** [comment]
This should be fixed in the latest version (1.0.0) . If you're still having the problem, please reopen this issue.
