### ISSUE TITLE
false positive with fact in map function.

### ISSUE THREAD

**Issue by traylenator** [mmckinst/puppet-lint-legacy_facts-check#34]
With `puppet-lint-legacy_facts-check (1.0.3)`

The following

```pupet
$_generic_maps = $email_with_fqdn.map | $_user | { "${_user}@cern.ch ${_user}@${facts['fqdn']}" }
```

reports:

```
manifests/mta.pp:44:legacy_facts:WARNING:legacy fact
```

**Comment by mmckinst** [comment]
AFAICT this is working as expected, meaning `$facts['fqdn']` is a legacy fact and it has been replaced with `$facts['networking']['fqdn']`. https://puppet.com/docs/facter/3.11/core_facts.html shows it in the legacy facts column. Is there something indicating its no longer considered legacy?

**Comment by duritong** [comment]
it's rather surprising that such a central fact is now considered legacy and everybody now has to write more verbose. This is more than 12 years of muscle memory that needs to change ;)

But yeah you are right that puppet calls it a legacy fact. The questions is whether it should be enforced this way.

**Comment by traylenator** [comment]
Forgot about this, indeed should be closed from my point of view.
