### ISSUE TITLE
puppet-lint fails with NoMethodError: undefined method `[]' for nil:NilClass when fact names are enclosed in double quotes

### ISSUE THREAD

**Issue by bart2** [mmckinst/puppet-lint-legacy_facts-check#6]
Example code:
`$test1 = $facts["test1"],`

Observed failure:

> rake lint
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
rake aborted!
NoMethodError: undefined method `[]' for nil:NilClass
/Library/Ruby/Gems/2.0.0/gems/puppet-lint-legacy_facts-check-0.0.2/lib/puppet-lint/plugins/legacy_facts.rb:92:in `block in check'
/Library/Ruby/Gems/2.0.0/gems/puppet-lint-legacy_facts-check-0.0.2/lib/puppet-lint/plugins/legacy_facts.rb:86:in `each'
/Library/Ruby/Gems/2.0.0/gems/puppet-lint-legacy_facts-check-0.0.2/lib/puppet-lint/plugins/legacy_facts.rb:86:in `check'
/Library/Ruby/Gems/2.0.0/gems/puppet-lint-2.1.0/lib/puppet-lint/checkplugin.rb:21:in `run'
/Library/Ruby/Gems/2.0.0/gems/puppet-lint-2.1.0/lib/puppet-lint/checks.rb:58:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/puppet-lint-2.1.0/lib/puppet-lint/checks.rb:56:in `each'
/Library/Ruby/Gems/2.0.0/gems/puppet-lint-2.1.0/lib/puppet-lint/checks.rb:56:in `run'
/Library/Ruby/Gems/2.0.0/gems/puppet-lint-2.1.0/lib/puppet-lint.rb:191:in `run'
/Library/Ruby/Gems/2.0.0/gems/puppet-lint-2.1.0/lib/puppet-lint/tasks/puppet-lint.rb:79:in `block (3 levels) in define'
/Library/Ruby/Gems/2.0.0/gems/puppet-lint-2.1.0/lib/puppet-lint/tasks/puppet-lint.rb:77:in `each'
/Library/Ruby/Gems/2.0.0/gems/puppet-lint-2.1.0/lib/puppet-lint/tasks/puppet-lint.rb:77:in `block (2 levels) in define'
/Library/Ruby/Gems/2.0.0/gems/puppet-lint-2.1.0/lib/puppet-lint/tasks/puppet-lint.rb:71:in `block in define'
/Library/Ruby/Gems/2.0.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => lint
(See full trace by running task with --trace)

**Comment by bart2** [comment]
https://github.com/mmckinst/puppet-lint-legacy_facts-check/pull/7

**Comment by mmckinst** [comment]
closed in version 0.0.3 https://github.com/mmckinst/puppet-lint-legacy_facts-check/pull/8 .
